# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  index: Jean's Note
  en: Jean's Note
  ko: Jean의 노트
  fr: Son petit cahier
  zh: 她的笔记
  ja: 彼女のノート
subtitle:
  en: jeannryu.github.io
  ko: jeannryu.github.io
  fr: jeannryu.github.io
  zh: jeannryu.github.io
  ja: jeannryu.github.io
email: jeann.tech@gmail.com
description:
  index: 
  en: 
  ko: 
  fr: 
  zh: 
  ja: 
index:
  en: en.html
  ko: ko.html
  fr: fr.html
  zh: zh.html
  ja: ja.html
feed:
  en: /feed.xml
  ko: /feed-ko.xml
  fr: /feed-fr.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeanryu.github.io" # the base hostname & protocol for your site
linkedin_username: jeannryu
github_username: jeannryu
instagram_username: jeannryu
youtube_username: UCGdBK4vq7JSDxVzCS2lg3Vg
facebook_username: ed2fd709

# Build settings
markdown: kramdown
